apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotscience-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: dotscience-operator
  template:
    metadata:
      labels:
        name: dotscience-operator
    spec:
      serviceAccountName: dotscience-operator
      containers:
        - name: dotscience-operator
          image: registry.connect.redhat.com/dotscience/dotscience-operator-ubi8:0.1.0
          command:
          - dotscience-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "dotscience-operator"
          resources:
            limits:
              cpu: 600m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
