apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotscience-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: dotscience-operator
  template:
    metadata:
      labels:
        name: dotscience-operator
    spec:
      serviceAccountName: dotscience-operator
      containers:
        - name: dotscience-operator
          # Replace this with the built image name
          image: quay.io/dotmesh/dotscience-operator:latest
          command:
          - dotscience-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "dotscience-operator"
