apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dotscience-operator
subjects:
- kind: ServiceAccount
  name: dotscience-operator
  namespace: default
roleRef:
  kind: ClusterRole
  name: dotscience-operator
  apiGroup: rbac.authorization.k8s.io
